### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by joshmedeski** [skanehira/denops-gh.vim#53]
## 🐛 Summary
I can not get this project to run properly.

## 💔 Enviroment
- Vim/Neovim Version: NVIM v0.7.2
- OS: macOS 12.5 (21G72)

## 👀 Steps
1. Open new buffer with the following format: `gh://:owner/:repo/issues` 
2. Buffer is blank

## 🆗 Expected
Show the issues for a repo

## 🚑 Actual
Blank buffer

---

Is there something I'm missing? I've set up all the dependencies and plugins correctly, but nothing happens when I open the buffers.

**Comment by skanehira** [comment]
Maybe cause is https://github.com/skanehira/denops-gh.vim/issues/52

**Comment by skanehira** [comment]
Fixed in #0741f95

**Comment by joshmedeski** [comment]
Thanks! Excited to experiment with this plugin.
